#!/usr/bin/env python3
"""D-106 end-to-end integration test runner.

Sends real Telegram messages to the CLIVE bot as the owner user and verifies all
six D-106 sign-off criteria without manual interaction. Results are printed to
stdout and sent as a Telegram message to your Saved Messages.

SETUP (one-time):
  1. Get API credentials from https://my.telegram.org → App configuration
  2. pip install -r tests/e2e/requirements.txt
  3. python tests/e2e/generate_session.py  (interactive, once)
  4. Copy the printed TELEGRAM_SESSION_STRING into your environment

REQUIRED ENV VARS:
  TELEGRAM_API_ID            — integer from my.telegram.org
  TELEGRAM_API_HASH          — string from my.telegram.org
  TELEGRAM_SESSION_STRING    — generated by generate_session.py (one-time)
  CLIVE_BOT_USERNAME         — e.g. @my_clive_bot

OPTIONAL ENV VARS:
  CLIVE_POSTGRES_CONTAINER   — default: clive-postgres
  CLIVE_MINIO_CONTAINER      — default: clive-minio
  MINIO_RAW_BUCKET           — default: clive-raw-store
  REPLY_TIMEOUT              — seconds to wait for bot reply, default: 60
  SKIP_MINIO_CHECK           — set to 1 to skip MinIO object verification
"""

from __future__ import annotations

import asyncio
import os
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field

from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.tl.types import Message

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

API_ID = int(os.environ["TELEGRAM_API_ID"])
API_HASH = os.environ["TELEGRAM_API_HASH"]
SESSION_STRING = os.environ["TELEGRAM_SESSION_STRING"]
BOT_USERNAME = os.environ["CLIVE_BOT_USERNAME"]

POSTGRES_CONTAINER = os.environ.get("CLIVE_POSTGRES_CONTAINER", "clive-postgres")
MINIO_CONTAINER = os.environ.get("CLIVE_MINIO_CONTAINER", "clive-minio")
MINIO_BUCKET = os.environ.get("MINIO_RAW_BUCKET", "clive-raw-store")

REPLY_TIMEOUT = int(os.environ.get("REPLY_TIMEOUT", "60"))
SKIP_MINIO = os.environ.get("SKIP_MINIO_CHECK", "0") == "1"

THROWAWAY_FILENAME = "d106_throwaway_test.txt"
THROWAWAY_MARKER = "CLIVE_D106_TEST_MARKER_XK7Q"


# ---------------------------------------------------------------------------
# Result tracking
# ---------------------------------------------------------------------------

@dataclass
class TestResult:
    name: str
    passed: bool
    detail: str = ""


_results: list[TestResult] = []


def record(name: str, passed: bool, detail: str = "") -> None:
    _results.append(TestResult(name=name, passed=passed, detail=detail))
    icon = "✅" if passed else "❌"
    suffix = f" — {detail}" if detail else ""
    print(f"  {icon} {name}{suffix}")


# ---------------------------------------------------------------------------
# DB helpers (via docker exec psql)
# ---------------------------------------------------------------------------

def _psql(query: str) -> str:
    result = subprocess.run(
        [
            "docker", "exec", POSTGRES_CONTAINER,
            "psql", "-U", "postgres", "-d", "clive", "-t", "-c", query,
        ],
        capture_output=True, text=True, timeout=15,
    )
    if result.returncode != 0:
        raise RuntimeError(f"psql failed: {result.stderr.strip()}")
    return result.stdout


def chunk_count_for(filename: str) -> int:
    out = _psql(f"SELECT count(*) FROM clive_search.chunks WHERE source_key LIKE '%/{filename}';")
    for line in out.splitlines():
        line = line.strip()
        if line.isdigit():
            return int(line)
    return -1


def source_key_for(filename: str) -> str | None:
    out = _psql(
        f"SELECT source_key FROM clive_search.chunks "
        f"WHERE source_key LIKE '%/{filename}' LIMIT 1;"
    )
    for line in out.splitlines():
        line = line.strip()
        if "/" in line and filename in line:
            return line
    return None


def list_db_documents() -> list[tuple[str, int]]:
    """Return [(filename, chunk_count)] for all documents."""
    out = _psql(
        "SELECT source_key, count(*) "
        "FROM clive_search.chunks "
        "GROUP BY source_key ORDER BY source_key;"
    )
    docs: list[tuple[str, int]] = []
    for line in out.splitlines():
        line = line.strip()
        if "|" in line and "/" in line:
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 2:
                sk = parts[0]
                fname = sk.split("/", 1)[-1] if "/" in sk else sk
                try:
                    docs.append((fname, int(parts[1])))
                except ValueError:
                    pass
    return docs


def latest_feedback_row() -> str | None:
    """Return the most recent feedback row as a string, or None."""
    out = _psql(
        "SELECT feedback_id, retrieval_event_id, feedback_type "
        "FROM clive_state.feedback "
        "ORDER BY submitted_at DESC LIMIT 1;"
    )
    for line in out.splitlines():
        if "poor_quality" in line:
            return line.strip()
    return None


def audit_event_rows() -> list[tuple[str, str]]:
    """Return [(event_type, source_block)] for D-106 relevant events."""
    relevant = (
        "'action.pending','action.confirmation_requested','action.owner_response',"
        "'action.confirmed','action.rejected','deletion.complete','deletion.not_found',"
        "'feedback.explicit'"
    )
    out = _psql(
        f"SELECT event_type, source_block::text "
        f"FROM clive_audit.event_log "
        f"WHERE event_type IN ({relevant}) "
        f"ORDER BY timestamp DESC LIMIT 20;"
    )
    rows: list[tuple[str, str]] = []
    for line in out.splitlines():
        line = line.strip()
        if "|" in line:
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 2:
                rows.append((parts[0], parts[1]))
    return rows


# ---------------------------------------------------------------------------
# MinIO helper (via docker run minio/mc inside minio's network namespace)
# ---------------------------------------------------------------------------

def _get_minio_creds() -> tuple[str, str]:
    user = subprocess.run(
        ["docker", "exec", MINIO_CONTAINER, "printenv", "MINIO_ROOT_USER"],
        capture_output=True, text=True, timeout=5,
    ).stdout.strip()
    passwd = subprocess.run(
        ["docker", "exec", MINIO_CONTAINER, "printenv", "MINIO_ROOT_PASSWORD"],
        capture_output=True, text=True, timeout=5,
    ).stdout.strip()
    return user, passwd


def minio_object_gone(source_key: str) -> bool:
    """Return True if the object no longer exists in MinIO."""
    user, passwd = _get_minio_creds()
    result = subprocess.run(
        [
            "docker", "run", "--rm",
            "--network", f"container:{MINIO_CONTAINER}",
            "-e", f"MC_HOST_local=http://{user}:{passwd}@localhost:9000",
            "minio/mc", "ls", f"local/{MINIO_BUCKET}/{source_key}",
        ],
        capture_output=True, text=True, timeout=30,
    )
    # mc exits non-zero and prints nothing if the object is absent
    return source_key not in result.stdout


# ---------------------------------------------------------------------------
# Telegram helpers
# ---------------------------------------------------------------------------

async def _last_id(client: TelegramClient, bot) -> int:
    msgs = await client.get_messages(bot, limit=1)
    return msgs[0].id if msgs else 0


async def _send(client: TelegramClient, bot, text: str) -> int:
    """Send text and return the message ID we sent (used as poll baseline)."""
    sent = await client.send_message(bot, text)
    await asyncio.sleep(1)
    return sent.id


async def wait_for_reply(
    client: TelegramClient,
    bot,
    after_id: int,
    timeout: int = REPLY_TIMEOUT,
    contains: str | None = None,
) -> Message | None:
    """Poll for any new bot message after `after_id` that optionally contains `contains`."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        msgs = await client.get_messages(bot, limit=10, min_id=after_id)
        for msg in sorted(msgs, key=lambda m: m.id):
            if not msg.text:
                continue
            if contains is None or contains.lower() in msg.text.lower():
                return msg
        await asyncio.sleep(2)
    return None


# ---------------------------------------------------------------------------
# Throwaway document setup
# ---------------------------------------------------------------------------

async def ensure_throwaway(client: TelegramClient, bot) -> bool:
    """Ensure the throwaway test document is ingested. Returns True on success."""
    if chunk_count_for(THROWAWAY_FILENAME) > 0:
        print(f"  → {THROWAWAY_FILENAME} already in DB")
        return True

    print(f"  → Ingesting {THROWAWAY_FILENAME}...")
    content = (
        "D-106 automated end-to-end test document.\n"
        "This file exists solely for the automated test suite.\n"
        f"Marker: {THROWAWAY_MARKER}\n"
        "It will be deleted as part of criterion 3.\n"
    )

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", prefix="d106_throwaway_test", delete=False
    ) as f:
        f.write(content)
        tmp = f.name

    import shutil
    target = os.path.join(os.path.dirname(tmp), THROWAWAY_FILENAME)
    shutil.move(tmp, target)

    baseline = await _last_id(client, bot)
    await client.send_file(bot, target, caption="/ingest")
    os.unlink(target)

    reply = await wait_for_reply(
        client, bot, baseline, timeout=120, contains=THROWAWAY_FILENAME
    )
    if reply and "ingested" in reply.text.lower():
        print(f"  → Ingested: {reply.text.strip()[:80]}")
        return True

    print(f"  → Ingest failed or timed out. Reply: {reply.text[:80] if reply else 'None'}")
    return False


# ---------------------------------------------------------------------------
# Criterion 4 — Not-found path
# ---------------------------------------------------------------------------

async def run_criterion_4(client: TelegramClient, bot) -> None:
    print("\n[C4] Not-found path")
    nonexistent = "this_file_does_not_exist_d106.pdf"
    sent_id = await _send(client, bot, f"/delete {nonexistent}")
    reply = await wait_for_reply(client, bot, sent_id, timeout=20)

    if reply and "found" in reply.text.lower() and nonexistent in reply.text:
        record("C4: not-found reply", True, reply.text.strip()[:60])
    else:
        record("C4: not-found reply", False, reply.text.strip()[:60] if reply else "timeout")


# ---------------------------------------------------------------------------
# Criterion 2 — Cancel path
# ---------------------------------------------------------------------------

async def run_criterion_2(client: TelegramClient, bot, preserve_filename: str) -> None:
    print(f"\n[C2] Cancel path — {preserve_filename}")

    before = chunk_count_for(preserve_filename)

    sent_id = await _send(client, bot, f"/delete {preserve_filename}")
    prompt = await wait_for_reply(client, bot, sent_id, timeout=30, contains="confirm")
    if not prompt:
        record("C2: confirmation prompt received", False, "timeout")
        return
    record("C2: confirmation prompt received", True, prompt.text.strip()[:60])

    sent_id = await _send(client, bot, "/cancel_delete")
    cancel_reply = await wait_for_reply(client, bot, sent_id, timeout=20, contains="cancel")
    if cancel_reply:
        record("C2: cancel acknowledged", True, cancel_reply.text.strip()[:60])
    else:
        record("C2: cancel acknowledged", False, "timeout or unexpected reply")

    after = chunk_count_for(preserve_filename)
    record(
        "C2: DB count unchanged",
        after == before,
        f"before={before} after={after}",
    )


# ---------------------------------------------------------------------------
# Criterion 3 — Confirmed deletion
# ---------------------------------------------------------------------------

async def run_criterion_3(client: TelegramClient, bot) -> None:
    print(f"\n[C3] Confirmed deletion — {THROWAWAY_FILENAME}")

    source_key = source_key_for(THROWAWAY_FILENAME)
    before = chunk_count_for(THROWAWAY_FILENAME)

    sent_id = await _send(client, bot, f"/delete {THROWAWAY_FILENAME}")
    prompt = await wait_for_reply(client, bot, sent_id, timeout=30, contains="confirm")
    if not prompt:
        record("C3: confirmation prompt received", False, "timeout")
        return
    record("C3: confirmation prompt received", True)

    sent_id = await _send(client, bot, "/confirm_delete")

    # Immediate "Confirmed. Deleting..."
    ack = await wait_for_reply(client, bot, sent_id, timeout=15, contains="Confirmed")
    if ack:
        record("C3: 'Confirmed. Deleting...' ack", True)
        baseline = ack.id
    else:
        record("C3: 'Confirmed. Deleting...' ack", False, "not received")
        baseline = sent_id

    # Async "Deleted. <filename> removed (N chunk(s) purged)."
    done = await wait_for_reply(client, bot, baseline, timeout=90, contains="Deleted")
    if done and THROWAWAY_FILENAME in done.text:
        record("C3: deletion complete message", True, done.text.strip()[:80])
    else:
        record(
            "C3: deletion complete message",
            False,
            done.text.strip()[:80] if done else "timeout",
        )

    # DB: chunks = 0
    after = chunk_count_for(THROWAWAY_FILENAME)
    record("C3: DB chunks = 0", after == 0, f"count={after}")

    # MinIO: object gone
    if not SKIP_MINIO:
        if source_key:
            try:
                gone = minio_object_gone(source_key)
                record("C3: MinIO object absent", gone, source_key[:60] if not gone else "confirmed absent")
            except Exception as exc:
                record("C3: MinIO object absent", False, str(exc)[:80])
        else:
            record("C3: MinIO object absent", False, "source_key not recorded before deletion")
    else:
        print("  ⏭  MinIO check skipped (SKIP_MINIO_CHECK=1)")

    # Retrievability: send a query only the throwaway could answer
    sent_id = await _send(client, bot, f"What is {THROWAWAY_MARKER}?")
    retrieval = await wait_for_reply(client, bot, sent_id, timeout=60)
    if retrieval:
        t = retrieval.text.lower()
        not_found = any(
            kw in t
            for kw in ("don't know", "no relevant", "⚠️", "general knowledge", "cannot find", "not find", "no information")
        ) or "⚠️" in retrieval.text
        record("C3: marker not retrievable", not_found, retrieval.text.strip()[:80])
    else:
        record("C3: marker not retrievable", False, "timeout on retrieval query")


# ---------------------------------------------------------------------------
# Criterion 5 — Block 18 feedback
# ---------------------------------------------------------------------------

async def run_criterion_5(client: TelegramClient, bot) -> None:
    print("\n[C5] Block 18 feedback")

    # Prime _last_retrieval with a real query
    sent_id = await _send(client, bot, "What do you know about CLIVE?")
    query_reply = await wait_for_reply(client, bot, sent_id, timeout=REPLY_TIMEOUT)
    if not query_reply:
        record("C5: retrieval query replied", False, "timeout")
        return
    record("C5: retrieval query replied", True, query_reply.text.strip()[:40])

    # /bad
    sent_id = await _send(client, bot, "/bad")
    bad_reply = await wait_for_reply(client, bot, sent_id, timeout=20)
    if bad_reply and ("noted" in bad_reply.text.lower() or "quality" in bad_reply.text.lower()):
        record("C5: /bad acknowledged", True, bad_reply.text.strip()[:60])
    else:
        record("C5: /bad acknowledged", False, bad_reply.text.strip()[:60] if bad_reply else "timeout")

    # DB row
    row = latest_feedback_row()
    record("C5: feedback row in DB", row is not None, row[:60] if row else "not found")

    # Edge case: /start → /bad → guidance (no prior retrieval in new session)
    sent_id = await _send(client, bot, "/start")
    await wait_for_reply(client, bot, sent_id, timeout=10, contains="Ready")

    sent_id = await _send(client, bot, "/bad")
    no_ret = await wait_for_reply(client, bot, sent_id, timeout=20, contains="No recent")
    record(
        "C5: /bad without retrieval → guidance",
        no_ret is not None and "no recent" in no_ret.text.lower(),
        no_ret.text.strip()[:60] if no_ret else "timeout or wrong reply",
    )


# ---------------------------------------------------------------------------
# Criterion 6 — Audit trail
# ---------------------------------------------------------------------------

async def run_criterion_6() -> None:
    print("\n[C6] Audit trail")

    required = {
        "action.pending",
        "action.confirmation_requested",
        "action.owner_response",
        "action.confirmed",
        "action.rejected",
        "deletion.complete",
        "feedback.explicit",
    }

    rows = audit_event_rows()
    found: set[str] = set()
    all_have_source_block = True

    for event_type, source_block in rows:
        if event_type in required:
            found.add(event_type)
        if not source_block or source_block.lower() in ("", "null"):
            all_have_source_block = False

    missing = required - found
    record(
        "C6: all required event types logged",
        not missing,
        f"found={len(found)}/7" + (f" missing={missing}" if missing else ""),
    )
    record(
        "C6: all events have source_block",
        all_have_source_block,
        "ok" if all_have_source_block else "some rows missing source_block",
    )


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def _build_report() -> str:
    passed = sum(1 for r in _results if r.passed)
    total = len(_results)
    lines = [
        f"D-106 E2E Test Report — {passed}/{total} passed",
        "─" * 52,
    ]
    for r in _results:
        icon = "✅" if r.passed else "❌"
        suffix = f" — {r.detail}" if r.detail else ""
        lines.append(f"{icon} {r.name}{suffix}")
    lines.append("─" * 52)
    if passed == total:
        lines.append("ALL PASSED — v0.3 ready for D-106 sign-off ✅")
    else:
        lines.append(f"{total - passed} FAILURE(S) — see above ❌")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main() -> None:
    print("D-106 E2E Test Runner")
    print("=" * 52)

    async with TelegramClient(StringSession(SESSION_STRING), API_ID, API_HASH) as client:
        bot = await client.get_entity(BOT_USERNAME)
        me = await client.get_me()
        print(f"Authenticated as: {me.first_name} (@{me.username})")
        print(f"Bot: {BOT_USERNAME}")

        # Prerequisites
        print("\n[Setup] Checking DB state...")
        docs = list_db_documents()
        for fname, count in docs:
            print(f"  {fname} ({count} chunks)")

        await ensure_throwaway(client, bot)

        # Re-read after potential ingest
        docs = list_db_documents()
        preserve = next(
            (fname for fname, _ in docs if fname != THROWAWAY_FILENAME), None
        )
        if preserve is None:
            print(
                "WARNING: No permanent document found for criterion 2 cancel path.\n"
                "Ingest a permanent document before running this suite.\n"
                "Using throwaway as fallback — criterion 2 will run but document "
                "will be deleted before criterion 3 gets to it if C2 fails."
            )
            preserve = THROWAWAY_FILENAME

        print(f"\n  Throwaway (for C3 delete): {THROWAWAY_FILENAME}")
        print(f"  Preserve  (for C2 cancel):  {preserve}")

        # Run criteria
        await run_criterion_4(client, bot)
        await run_criterion_2(client, bot, preserve)
        await run_criterion_3(client, bot)
        await run_criterion_5(client, bot)
        await run_criterion_6()

        # Report
        report = _build_report()
        print("\n" + report)

        await client.send_message("me", report)
        print("\nReport sent to Telegram Saved Messages.")

    passed = sum(1 for r in _results if r.passed)
    sys.exit(0 if passed == len(_results) else 1)


if __name__ == "__main__":
    asyncio.run(main())
